version: "3.9"

volumes:
  mariadb:
  nextcloud:
  
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    networks:
      - backend

  nextcloud:
    container_name: nextcloud
    image: nextcloud:24.0-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_HOST
    networks:
      - frontend
      - backend
    depends_on:
      - mariadb
      - haproxy

  haproxy:
    container_name: haproxy
    image: haproxy:2.6
    configs:
      - source: haproxyconf
        target: /usr/local/etc/haproxy/haproxy.cfg
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
 
configs:
  haproxyconf:
    file: ./haproxy/haproxy.cfg

networks:
  frontend:
  backend:
