version: "3.9"

volumes:
  mariadb:
  nextcloud:
  haproxy:
  
services:
  mariadb:
    image: mariadb:10.8-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  nextcloud:
    image: nextcloud:24.0-apache
    restart: always
    #    ports:
      #  - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - frontend
      - backend

  haproxy:
    image: haproxy:2.6
    restart: always
    ports:
      - 8080:80
    networks:
      - frontend
    volumes:
      - haproxy:/etc/haproxy

networks:
  frontend:
  backend:
